package com.acc.lkm.empentity;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
@Entity
@Table(name="Employeedet")
public class EmpEntity {
	public EmpEntity() {
		super();
	}
    @Id
    @GeneratedValue
	private Integer empid;//empid will be autoincremented and autogenerated
	private String empname;
	private String role;
	private Double salary;
	@Temporal(TemporalType.DATE)//will drop the time value
	private Date Hiredate;

	public Integer getEmpid() {
		return empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	public String getEmpname() {
		return empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public  Double getSalary() {
		return salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

	public Date getHiredate() {
		return Hiredate;
	}

	public void setHiredate(Date hiredate) {
		Hiredate = hiredate;
	}

}
